name = "CatmullClark"
uuid = "88c4633f-7fb9-5883-9312-8d9642ed46e5"
authors = ["William Herrera <wherrera@alahonua.com>"]
version = "0.1.6"

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
ThreadSafeDicts = "4239201d-c60e-5e0a-9702-85d713665ba7"

[compat]
julia = ">= 1"
Makie = ">= 0.17"
GeometryBasics = ">= 0.4"
ThreadSafeDicts = ">= 0.1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Test"]
