authors = ["William Herrera <wherrera@alahonua.com>"]
name = "CatmullClark"
uuid = "88c4633f-7fb9-5883-9312-8d9642ed46e5"
version = "0.0.1"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
julia = "1"

[targets]
test = ["Pkg", "Test"]

